config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :shoes
  root to: "shoes#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :shoes
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  enum condition: {brand_new: 1, used: 0}
  belongs_to :location
  belongs_to :user
  has_many_attached :picture

  def shoe_attachment_path
    picture.attached? ? picture[0] : "default.jpeg"

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shoes
  has_one_attached :picture
  def user_picture_attach 
    picture.attached? ? picture : "avatar.jpeg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters,
                if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:picture, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_user_shoes, only: [:edit, :update, :destroy]
  before_action :set_vars, only: [:new, :create, :edit, :update]
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    # @shoes = Shoe.all
    @q =  Shoe.ransack(params[:q])
    @shoes = @q.result(distinct: true)
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = current_user.shoes.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user_shoes
    id = params[:id]
    @shoe = current_user.shoes.find_by_id(id)

    if @shoe == nil
        redirect_to shoes_path
    end
end
  def set_vars
    @conditions = Shoe.conditions.keys
    @locations = Location.all
end

    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shoe_params
      params.require(:shoe).permit(:brand, :model, :condition, :price, :description, :location_id, picture: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sneakertrade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render  "shared/error" %>
  <%= render  "shared/navbar" %>
  <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_error.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
  <%= link_to  root_path %>
    <button>Shoes_store</button>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        <%if user_signed_in? %>
        <%= link_to  "Profile",  edit_user_registration_path %>
        <%= link_to  "Sign Out", destroy_user_session_path, :method => :delete  %>
        <%else%>
            <%= link_to  "Sign In", new_user_session_path  %>
            <%= link_to  "Sign Up", new_user_registration_path %>
        
        <%end%>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shoes/_form.html.erb
<%= form_with(model: shoe, local: true) do |form| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <% @conditions.each do |option| %>
    <div>
    <%= form.radio_button :condition, option %>
    <%= form.label "condition_#{option}".to_sym, option%>
    <div>
    <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
     <%= form.label :location_id %>  
    <%= form.select(:location_id, @locations.map{|l| [l.state, l.id]}) %> 
  </div>
   <div class="field">
     <%= form.label :picture %>  
    <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg', multiple: true %> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoes</h1>
<%= link_to  "New_shoe", new_shoe_path %>

<%= search_form_for @q do |f| %>

  # Search if the name field contains...
  <%= f.label "Find shoe:" %>
  <%= f.search_field :brand_or_model_or_description_cont %>


  <%= f.submit %>
<% end %>

<div class="container">
  <% @shoes.each do |shoe| %>
  <div class="card" style="
  border-radius: 20px;
    box-shadow: 2px 2px 7px black;
    width: 300px;
    position: relative;
    margin: 10px;">
    <div class="card-image" style="width: 300px;border-radius: 20px 20px 0px 0px">
    <figure class="image is-4by3">
      <%#= image_tag shoe.picture if shoe.picture.attached? %> 
      <%= image_tag shoe.shoe_attachment_path%>

    </figure>
  </div>
    <div class="card-content" style="height:300px">
    <ul>
     <li> <%= shoe.brand %></li>
      <li><%= shoe.user.email %> - <%= image_tag shoe.user.user_picture_attach%></li>
     <li> <%= shoe.model %></li>
     <li> <%= shoe.condition %></li>
     <li> <%= shoe.price %></li>
      <li><%= shoe.description %></li>
      <li><%= shoe.location.state %></li>
      </ul>
    </div>
    <div class="card-footer" style="height:50px">
      <%= link_to 'Show', shoe, class:"card-footer-item" %>
      <% if user_signed_in? %>
      <% if shoe.user == current_user %>
      <%= link_to 'Edit', edit_shoe_path(shoe), class:"card-footer-item"  %>
      <%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' }, class:"card-footer-item"  %>
      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>

  <br>


</div>

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @shoe.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @shoe.model %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @shoe.condition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shoe.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @shoe.location.state %>
</p>
<p>
 <strong>Pictures:</strong>
 <%@shoe.picture.each do |s|%>
 <%= image_tag  s %>

 <%#for picture in @shoe.picture do%>
 <%#= image_tag  picture %>
 <%end%>
</p>
<%if current_user == @shoe.user%>
<%= link_to 'Destroy', @shoe, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%end%>
<%= link_to 'Back', shoes_path %>